# .github/workflows/run-python.yml
name: Run Python Script

# 触发条件：当推送到 main 分支时运行
on:
  push:
    branches: [ main ]
  # 也可以设置为每天自动运行（定时任务）
  schedule:
    - cron: '0 9 * * *'  # 每天 UTC 时间 9:00 AM 运行

# 任务定义
jobs:
  run-python:
    # 运行环境
    runs-on: ubuntu-latest
    
    # 任务步骤
    steps:
      # 1. 检出仓库代码
      - name: Checkout code
        uses: actions/checkout@v4
        
      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # 指定 Python 版本

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4. 运行 Python 脚本
      - name: Run Python script
        run: python get_live_stream.py
